#!/usr/bin/env bash

set -eou pipefail

: "${RESULTS_NAME="test-results"}"

if [[ -n "${TESTING_PATH:-}" ]]; then
    DIR="$TESTING_PATH"
else
    # figure out app folder (remove last 3 directories)
    DIR=$(echo "$0" | rev | cut -d'/' -f4- | rev)
fi

FLAGS=("-v")
if [[ -n "${TAGS:-}" ]]; then
  FLAGS+=("-tags=${TAGS}")
fi

[ -d "$DIR"/reports ] || mkdir "$DIR"/reports

go test "$@" "${FLAGS[@]}" "./${DIR}/..." 2>&1 | tee >(go-junit-report > "${DIR}/reports/${RESULTS_NAME}.xml")
